### ISSUE TITLE
Wording on sponsorship and hosting pages

### ISSUE THREAD

**Issue by aaevan** [BostonPython/about#11]
Sponsorship: The multiple etcs run into the next sentence and repetition of "to" is awkward.
`We have tables dedicated to beginning learners, to web development, to data science, to hardware, etc, etc. The unstructured time means that much...`

Sponsorship: Lose the passive voice/clarify wording: "they are being pitched too hard"
`Up to five minutes isn’t unheard of, but starts to feel long. People lose interest if they are being pitched too hard.`

Sponsorship: Extra "at all":
`If you have any questions at all, feel free to get in touch with the leadership team at leaders@bostonpython.com`

Hosting: pluralize guest "right tone you want to set for guest"
`Please consider whether this is the right tone you want to set for guest at an event open to the public.`

**Comment by nedbat** [comment]
Thanks, I just noticed the guest/guests thing and fixed before I saw this issue! :)

Do you want to make a pull request with these changes?

**Comment by nedbat** [comment]
I think these are all done now.
