### ISSUE TITLE
Add books to "Resources" page

### ISSUE THREAD

**Issue by bhrutledge** [BostonPython/about#16]
Ideally curated from recommendations from our members, maybe with a bias towards exercises and projects. For example:

https://greenteapress.com/wp/think-python-2e/
https://automatetheboringstuff.com/

Probably after PR #15 is merged

**Comment by jonkiparsky** [comment]
Brainstorming other possible adds

Cracking Codes With Python (No Starch) https://nostarch.com/crackingcodes
Impractical Python Projects (No Starch) https://nostarch.com/impracticalpythonprojects
Python the Hard Way (have to include some warning text, obvs)
Think Stats! (https://greenteapress.com/wp/think-stats-2e/)
Think Bayes! (http://greenteapress.com/wp/think-bayes/)

**Comment by bhrutledge** [comment]
#22 is a good start, so I'm closing this, but we can always add more.
