### ISSUE TITLE
Fix "Have a suggestion" footer layout on mobile

### ISSUE THREAD

**Issue by bhrutledge** [BostonPython/about#17]
The negative margin puts the text at the edge of viewport:

![Screen Shot 2019-11-01 at 8 48 38 AM](https://user-images.githubusercontent.com/1326704/68025973-a5db3500-fc84-11e9-9da8-56478762fe55.png)

https://github.com/BostonPython/about/blob/327094dc8a973488fd802a3bc67977e15f1243fa/assets/css/main.scss#L47-L51

**Comment by bhrutledge** [comment]
@nedbat How strongly do you feel about having the footer content with the page body? 😉 Might need a media query to do that...

**Comment by nedbat** [comment]
Oops, mobile.  I'll fix it.

**Comment by bhrutledge** [comment]
Fixed in #18
